### PR TITLE
WIP: Fix navigation/page structure

### PR DESCRIPTION
**Pull request by plutonik-a**
I'm trying to fix the page navigation. Currently adding some placeholder pages for testing reasons.

### CODE REVIEW

**Comment by srenatus** [comment]
Re: localization, with the usual

``` yaml
title:
  en: ...
  de: ...
```

in `nagivation.yml`, and `link.title[page.language]` in [`navigation.html`](https://github.com/refugee-emancipation/crowd-funding/blob/master/_includes/navigation.html#L45), would it work?

**Comment by plutonik-a** [comment]
Now we cross commented! Okay. I'll try it out, thanks!

**Comment by plutonik-a** [comment]
At the moment, page paths are strangely concatenated with `en`. I'm still a bit clueless....

**Comment by srenatus** [comment]
Ok, I'll look into it, too.

**Comment by plutonik-a** [comment]
Already merged in other PRs.

**Pull request closed without merging**
