### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by srenatus**
Travis CI offers a nice service for running builds and tests on commit ([see here](https://travis-ci.org/srenatus/crowd-funding)). This branch includes the configuration, but some setup has to be done with the refugees-emancipation account after merging to have Travis do something on new commits.

Followed the [Jekyll docs](http://jekyllrb.com/docs/continuous-integration/), mostly, also including html-proofer. These commits fix some of the errors found by html-proofer, but not all of them.

With the dependencies in place (needs nokogiri, so libxml2[-dev], libxslt[-dev], build-essential on Debian-ish systems), html-proofer can be run locally, I added it to the Gemfile. If the dependencies are troublesome, we could either run it on Travis only (see early commits) or add an "integration" group to the Gemfile.

### CODE REVIEW

**Comment by srenatus** [comment]
Thinking about it, just went with the `tests` group (Gemfile). README needs an update if this is merged.

**Comment by srenatus** [comment]
Fixed. So html-proofer apparently doesn't complain about unclosed tags.

**Comment by plutonik-a** [comment]
So, what does html-proofer do? Apparently, it's not some kind of validator.

**Comment by srenatus** [comment]
A [list of its tests is here](https://github.com/gjtorikian/html-proofer#whats-tested) - Is it needed? I don't know. It did catch some minor things, and there're still issues open...

**Comment by plutonik-a** [comment]
Yeah, just found the list. Maybe we should configure the validation tests to "strict" mode: http://www.nokogiri.org/tutorials/ensuring_well_formed_markup.html

**Comment by plutonik-a** [comment]
I would like to keep all the tests activated, because I used a Jekyll theme, which unfortunately needs a lot of improvements when it comes to accessibility and semantic markup.

**Comment by srenatus** [comment]
Nokogiri's strict mode doesn't find that, either...
https://gist.github.com/srenatus/61075ae95a73b31b2e4c

**Comment by srenatus** [comment]
Ok, took me a while, but vnu seems to be a rather thorough validator, judging from the mass of findings [here](https://travis-ci.org/srenatus/crowd-funding/builds/79634809). Can't really evaluate it, though... seems to make sense...

**Comment by srenatus** [comment]
I'll probably give this another go later. :)

**Pull request closed without merging**
