### PR TITLE
Press review

### PR DESCRIPTION
**Pull request by srenatus**
This makes use of the spreadsheet using client-side js.
Seemed like the most pragmatic way to get this done now.

TODO:
- Integration (nagivation)
- Better layout probably

### CODE REVIEW

**Comment by plutonik-a** [comment]
@srenatus Where do you suggest to solve the localization problem? As you see in my PR https://github.com/refugee-emancipation/crowd-funding/pull/56, I also need to work on that.

**Comment by srenatus** [comment]
@plutonik-a Localization of... press item captions? I'd suggest pushing that into the spreadsheet. I.e., have two captions there or one that works for all languages ("Artikel-Titel (German only)").
I guess two (and someday maybe more) captions is better, if we go with that, I can update this PR. Would you agree?

**Comment by plutonik-a** [comment]
Hm, I quite don't get your point. I was aiming at a general solution in the navigation or config.

**Comment by srenatus** [comment]
Moved to subpages branch, #61

**Pull request closed without merging**
