### PR TITLE
Banner tracking, including file-related data

### PR DESCRIPTION
**Pull request by srenatus**
Add _"Copy this to include our banner (and tracking pixel)"_-input field to banners

~~TODO: Something, somewhere went wrong with the list, I don't know why it looks weird: there's a line break "after" the `li`, before the `a`...?~~

### CODE REVIEW

**Comment by srenatus** [comment]
@plutonik-a @line-o Opinions, design improvements? :)

**Comment by plutonik-a** [comment]
> Opinions, design improvements? :)

The template `page` apparently isn't suitable for the download page.
The place, where `{{ content  }}` is inserted, seems very strange. 
I'll either try to improve the template or might as well create a new one :)

**Comment by plutonik-a** [comment]
Also, the `itemprop` Microdata doesn't seem to be used correctly here. All content will be surrounded by one `itemprop="articleSection"`, although we might want to place more than one article here, or even other  elements than `<article>`.

**Comment by plutonik-a** [comment]
Design: The accordion needs an arrow-icon to indicate its function -> classical solution.

**Comment by srenatus** [comment]
~~Please don't merge this right now, I'm trying to remove the need for https://github.com/refugee-emancipation/crowd-funding/pull/62/files#diff-69cb2c60ade563f7533c5f5bac421be4R6~~

**Pull request merged**
